import json
import re
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from google import genai
from google.genai import types
from llama_cpp import Llama

app = FastAPI()

# --- 1. SETUP LOCAL LLM (LAYER 2: COGNITIVE HINTS) ---
print("🧠 Loading Local Llama Model into Mac M1 Memory...")
try:
    llm = Llama(
        model_path="./llama-3.2-3b-instruct.Q4_K_M.gguf", 
        n_gpu_layers=-1, 
        n_ctx=2048,
        verbose=False 
    )
    print("✅ Local AI Model Loaded Successfully!")
except Exception as e:
    print(f"❌ Failed to load local model. Error: {e}")

# --- 2. SETUP CLOUD LLM (LAYER 3: VARK TRANSLATOR) ---
# GO TO: https://aistudio.google.com/ to get a free key
client = genai.Client(api_key="AIzaSyC1mru33yboj6RzNLj0xfjbXD7HHY4RPLU")

# --- 3. LAYER 1: DETERMINISTIC MATRIX ---
HINT_MATRIX = {
    "missing_ampersand_scanf": {
        "FOCUS": {1: "Check your scanf arguments.", 2: "Your scanf is missing an address operator.", 3: "Add an '&' before the variable name in scanf."},
        "OVERLOAD": {1: "There's a tiny typo in your scanf.", 2: "Look closely at the variable in scanf. It needs an '&'.", 3: "Take a breath. Add an '&' right before the variable inside scanf."},
        "CONFUSE": {1: "scanf needs to know *where* to store the input.", 2: "scanf requires memory addresses. You missed the '&' symbol.", 3: "Because scanf modifies variables, it needs their address. Put '&' before your variable."}
    }
}

def analyze_c_code(code: str):
    if re.search(r'scanf\s*\(\s*"[^"]+"\s*,\s*([A-Za-z0-9_]+)\s*\)', code):
        return "missing_ampersand_scanf"
    return None 

def is_valid_c_code(code: str) -> bool:
    if not code or len(code.strip()) < 5:
        return False
    c_keywords = ["#include", "main", "printf", "scanf", "return", "int ", "float ", "char ", "void ", "for(", "while(", "if("]
    return any(keyword in code for keyword in c_keywords)

# --- 4. LAYER 2 GENERATOR: LOCAL LLM ---
def get_local_ai_hint(code: str, state: str, attempt: int) -> str:
    prompt = f"""Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
You are an empathetic and expert C programming tutor. Analyze the student's code, cognitive state, and attempt number to provide a tailored, highly specific hint.

### Input:
Student Code:
{code}

Cognitive State: {state}
Attempt Number: {attempt}

### Response:
"""
    output = llm(prompt, max_tokens=150, stop=["### Instruction:"], echo=False)
    return output['choices'][0]['text'].strip()

# --- 5. LAYER 3 TRANSLATOR: GEMINI VARK FORMATTER ---
def format_hint_to_vark(code: str, vark: str, base_hint: str):
    print(f"🎨 Sending Base Hint to Gemini for {vark} formatting...")
    
    prompt = f"""
    You are a formatting engine. I am giving you a base hint generated by a tutor for a student's C code. 
    Your ONLY job is to convert this exact hint into the requested VARK learning style format.
    
    Code: {code}
    Base Hint to format: "{base_hint}"
    Requested VARK Style: {vark} (V=Visual, A=Audio, R=Reading, K=Kinesthetic)
    
    Output a JSON object strictly matching this format:
    {{
        "hint_text": "Refine the base hint to be short and empathetic.",
        "vark_mode": "{vark}",
        "media_content": "If V, output ONLY valid Mermaid.js graph syntax representing the code flow (e.g., graph TD; A-->B;). If A, write a supportive script to be read out loud. If K, write a physical instruction they must simulate. If R, output the detailed base hint."
    }}
    """
    
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
            config=types.GenerateContentConfig(response_mime_type="application/json")
        )
        return json.loads(response.text)
    except Exception as e:
        print(f"⚠️ Gemini Error: {e}")
        return {"hint_text": base_hint, "vark_mode": "R", "media_content": base_hint}

# --- 6. WEBSOCKET ROUTER ---
@app.websocket("/ws/hints")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    print("🟢 VS Code Webview connected!")
    
    try:
        while True:
            raw_data = await websocket.receive_text()
            data = json.loads(raw_data)
            
            code = data.get('code', '')
            state = data.get('state', 'FOCUS').upper()
            attempt = min(int(data.get('attempt', 1)), 3)
            vark_style = data.get('vark', 'R').upper() 
            
            if not is_valid_c_code(code):
                await websocket.send_text(json.dumps({
                    "error": "🛡️ Guardrail: Please submit valid C programming code."
                }))
                continue
            
            # --- THE PIPELINE ---
            
            # 1. Try to get a Matrix Hint
            detected_error = analyze_c_code(code)
            if detected_error and detected_error in HINT_MATRIX:
                base_hint = HINT_MATRIX[detected_error][state][attempt]
                print(f"⚡ Pipeline: Matrix generated base hint: {base_hint}")
                
            # 2. Fallback to Local Llama AI
            else:
                print("🧠 Pipeline: Asking Local Llama for base hint...")
                base_hint = get_local_ai_hint(code, state, attempt)
                print(f"🧠 Pipeline: Llama generated: {base_hint}")
            
            # 3. Translate the finalized hint to VARK using Gemini
            vark_payload = format_hint_to_vark(code, vark_style, base_hint)
            
            # 4. Send the package to VS Code
            await websocket.send_text(json.dumps({
                "status": "success",
                "ai_payload": vark_payload
            }))
            
    except WebSocketDisconnect:
        print("🔴 VS Code disconnected.")